# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1、iOS自定义播放器' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 1、iOS自定义播放器
  pod 'CLPlayer'
end
